# Generated by Django 3.2 on 2021-04-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiabox_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='community_name',
            field=models.CharField(default='NO COMMUNITY', max_length=50),
        ),
    ]
